In [1]:
import numpy as np
import pandas as pd

In [2]:
Data = pd.read_csv('Data.csv')
X = Data.iloc[:,:-1].values
Y = Data.iloc[:,-1].values
Y = Y.reshape(-1,1)
print(X)
print(Y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[[463.26]
 [444.37]
 [488.56]
 ...
 [429.57]
 [435.74]
 [453.28]]


In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=0)

In [8]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=150)
regressor.fit(X_train, Y_train)

C:\Users\saini\AppData\Local\Temp\ipykernel_20128\341427183.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor.fit(X_train, Y_train)


RandomForestRegressor(n_estimators=150)

In [9]:
Y_pred = regressor.predict(X_test)

In [10]:
from sklearn.metrics import r2_score
Score = r2_score(Y_test, Y_pred)
print(Score)

0.9653513672740862


In [11]:
default_n_estimators = regressor.n_estimators

print("Default value for n_estimators:", default_n_estimators)

Default value for n_estimators: 150


In [ ]:
# Default is 100